Add --version optional arg to set-version
Make it possible to run this macro non-interactively

diff --git a/git-release b/git-release
--- a/git-release
+++ b/git-release
@@ -3,9 +3,9 @@
 #
 usage() {
    cat <<EOF
-usage: git release version
-   or: git release branch
+usage: git release branch
    or: git release tag [-f] [-m <msg>]
+   or: git release set-version [--version <version>]
 
     Simple release oriented workflow.
 
@@ -64,9 +64,9 @@ main() {
 #
 subcommand() {
    case "$1" in
-      version)
+      set-version)
          shift
-         subcommand_version "$@"
+         subcommand_set_version "$@"
          ;;
       branch)
          shift
@@ -81,7 +81,7 @@ subcommand() {
          exit 0
          ;;
       *)
-         echo "error: Unknown subcommand: '$1'"
+         echo "error: unknown subcommand: '$1'"
          usage
          exit 1
          ;;
@@ -89,8 +89,14 @@ subcommand() {
 }
 
 # on master set new version, e.g. use to bump major version
-subcommand_version() {
-   local subcommand="version"
+subcommand_set_version() {
+   local subcommand="set-version"
+
+   local opts_spec="\
+git release set-version [--version <version>]
+--
+v,version=version the new version"
+   eval "$(echo "$opts_spec" | git rev-parse --parseopt -- "$@" || echo exit $?)"
 
    assert_master_branch
    assert_git_clean_work_tree
@@ -98,7 +104,29 @@ subcommand_version() {
    set_curr_version
    set_next_version $subcommand
 
-   ask_next_version NEXT_VERSION $subcommand
+   local next_version
+   while [[ $# > 1 ]]
+   do
+      name="$1"
+      shift
+
+      case $name in
+         -v)
+            next_version="$1"
+            assert_valid_version $next_version
+            shift
+            ;;
+         *)
+            ;;
+      esac
+   done
+
+   if [[ -n $next_version ]]
+   then
+      NEXT_VERSION=$next_version
+   else
+      ask_next_version NEXT_VERSION $subcommand
+   fi
 
    # on master
    update_version $NEXT_VERSION $MASTER_VERSION_POSTFIX
@@ -116,8 +144,6 @@ subcommand_branch() {
 
    set_curr_version
    set_next_version $subcommand
-
-   ask_next_version NEXT_VERSION $subcommand
 
    # on 'release/major.minor'
    git checkout -b ${RELEASE_BRANCH_PREFIX}${NEXT_BRANCH}
@@ -152,9 +178,8 @@ f,force       replace the tag if exists"
    set_curr_version
    set_next_version $subcommand
 
-   ask_next_version NEXT_VERSION $subcommand
-
    # on 'release/major.minor'
+   echo "Tagging branch with version: $CURR_VERSION"
    git tag "$@" $CURR_VERSION
    update_version $NEXT_VERSION $RELEASE_VERSION_POSTFIX
    git add $GIT_RELEASE_PROPERTIES
@@ -245,7 +270,7 @@ assert_valid_version() {
 
    if ! is_valid_version "$version"
    then
-      die "not valid version: $version"
+      die "not valid 'major.minor.patch' version format: '$version'"
    fi
 }
 
@@ -271,7 +296,7 @@ set_next_version() {
    minor=${split[1]}
    patch=${split[2]}
 
-   if [[ $subcommand == "branch" || $subcommand == version ]]
+   if [[ $subcommand == "branch" || $subcommand == set_version ]]
    then
       # e.g. 2.7
       NEXT_BRANCH="$major.$minor"
@@ -290,16 +315,7 @@ function ask_next_version {
    local subcommand="$2"
    local read_version _next_version
 
-   if [[ $subcommand == "branch" ]]
-   then
-      echo "Create new release branch: '${RELEASE_BRANCH_PREFIX}${NEXT_BRANCH}'"
-
-   elif [[ $subcommand == "tag" ]]
-   then
-      echo "Tag branch with version: $CURR_VERSION"
-   fi
-
-   read -e -p "Prepare '$(git_current_branch)' for future version: [$NEXT_VERSION] ? " read_version
+   read -e -p "Specify the next version of '$(git_current_branch)': [$NEXT_VERSION] ? " read_version
    _next_version=${read_version:-$NEXT_VERSION}
 
    assert_valid_version $_next_version
@@ -325,6 +341,8 @@ assert_release_properties() {
 #
 update_release_properties() {
    local version="$1"
+
+   echo "Next version of '$(git_current_branch)' is now version: $version"
    printf "# git-release generated file\nversion=%s\n" $version > $GIT_RELEASE_PROPERTIES
 }
 
